name: Password Check

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  password-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for passwords
        run: |
          PASSWORD_PATTERN='(password|pass|secret):[^\s]+'
          files_with_passwords=$(grep -Eirl "$PASSWORD_PATTERN" .)
          if [ -n "$files_with_passwords" ]; then
            echo "Error: Passwords found in the following files:"
            echo "$files_with_passwords"
            echo "Automatically discarding the last commit..."
            git revert --no-edit HEAD
            git push origin HEAD
          fi
